import Head from 'next/head'
import Cursor from "@/pages/Cursor";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Scissors game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="game-name">Rock paper scissors</h1>
        <div className="container-cursor">
          <Cursor />
        </div>
      </main>
    </div>
  )
}
